name: Unit test CI

on:
  push:
    branchs: [ v1.1.0 ]
  pull_request:
    branchs: [ v1.1.0 ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ 3.6 ]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/test.txt
      - name: Create Database
        run: |
          python manage_test.py makemigrations
          python manage_test.py migrate
      - name: Run Unit Tests
        run: |
          coverage run  manage_test.py test
          coverage report

